# Generated by Django 5.1.15 on 2026-06-17 12:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('landing_pages', '0001_initial'),
        ('organizations', '0001_initial'),
        ('templates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('voice', 'Voice'), ('qr_code', 'QR Code')], default='email', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=12)),
                ('description', models.TextField(blank=True, default='')),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('submission_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('bounce_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('email_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='templates.emailtemplate')),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='landing_pages.landingpage')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'campaign',
                'verbose_name_plural': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('sent', 'Sent'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('submitted', 'Submitted'), ('reported', 'Reported'), ('event', 'Event')], max_length=12)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='campaigns.campaign')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_activities', to='employees.employee')),
            ],
            options={
                'verbose_name': 'campaign activity',
                'verbose_name_plural': 'campaign activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='campaigns.campaign')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'campaign assignment',
                'verbose_name_plural': 'campaign assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', 'status'], name='campaigns_c_organiz_a8017f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['organization', '-created_at'], name='campaigns_c_organiz_60e4bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_campaign_org_name'),
        ),
        migrations.AddIndex(
            model_name='campaignactivity',
            index=models.Index(fields=['campaign', '-timestamp'], name='campaigns_c_campaig_0cf043_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignactivity',
            index=models.Index(fields=['employee', '-timestamp'], name='campaigns_c_employe_5bca19_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignassignment',
            index=models.Index(fields=['campaign', 'employee'], name='campaigns_c_campaig_274ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignassignment',
            index=models.Index(fields=['employee', 'campaign'], name='campaigns_c_employe_d80f9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaignassignment',
            constraint=models.UniqueConstraint(fields=('campaign', 'employee'), name='uq_assignment_campaign_employee'),
        ),
    ]
