# Generated by Django 5.1.15 on 2026-06-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='launched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
