# Generated by Django 5.1.15 on 2026-06-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_launched_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignactivity',
            name='metadata',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
