# Generated by Django 5.1.15 on 2026-06-17 12:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('category', models.CharField(choices=[('auth_portal', 'Auth Portal'), ('corporate_page', 'Corporate Page'), ('landing_page', 'Landing Page')], default='landing_page', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=512)),
                ('html_content', models.TextField(blank=True, default='')),
                ('css_content', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landing_pages', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'landing page',
                'verbose_name_plural': 'landing pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_credentials', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_page_visits', to='employees.employee')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='landing_pages.landingpage')),
            ],
            options={
                'verbose_name': 'landing page visit',
                'verbose_name_plural': 'landing page visits',
                'ordering': ['-visited_at'],
            },
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['organization', 'category'], name='landing_pag_organiz_74ef0f_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpage',
            index=models.Index(fields=['organization', 'is_active'], name='landing_pag_organiz_1f25a4_idx'),
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uq_landingpage_org_slug'),
        ),
        migrations.AddIndex(
            model_name='landingpagevisit',
            index=models.Index(fields=['landing_page', '-visited_at'], name='landing_pag_landing_c9dd1b_idx'),
        ),
        migrations.AddIndex(
            model_name='landingpagevisit',
            index=models.Index(fields=['landing_page', 'submitted_credentials'], name='landing_pag_landing_ce73d4_idx'),
        ),
    ]
