# Generated by Django 5.1.15 on 2026-06-21 20:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_update_risk_levels'),
        ('organizations', '0002_infrastructuresetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('phishing_awareness', 'Phishing Awareness'), ('security_basics', 'Security Basics'), ('social_engineering', 'Social Engineering'), ('data_protection', 'Data Protection')], default='phishing_awareness', max_length=25)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('content_type', models.CharField(choices=[('video', 'Video'), ('article', 'Article'), ('quiz', 'Quiz'), ('interactive', 'Interactive')], default='article', max_length=15)),
                ('content_url', models.URLField(blank=True, default='')),
                ('content_body', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='training.course')),
            ],
            options={
                'verbose_name': 'course module',
                'verbose_name_plural': 'course modules',
                'ordering': ['course', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='training.course')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_enrollments', to='employees.employee')),
            ],
            options={
                'verbose_name': 'training enrollment',
                'verbose_name_plural': 'training enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'category'], name='training_co_organiz_872618_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['organization', 'is_active'], name='training_co_organiz_13aa56_idx'),
        ),
        migrations.AddIndex(
            model_name='coursemodule',
            index=models.Index(fields=['course', 'order'], name='training_co_course__5f89cc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['employee', 'course'], name='training_tr_employe_a7f0cc_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['course', 'completed_at'], name='training_tr_course__e3f0ed_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingenrollment',
            index=models.Index(fields=['employee', 'completed_at'], name='training_tr_employe_ecc2c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingenrollment',
            constraint=models.UniqueConstraint(fields=('employee', 'course'), name='uq_enrollment_employee_course'),
        ),
    ]
