# Generated by Django 5.1.15 on 2026-06-17 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(blank=True, default='', max_length=255)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('risk_score', models.PositiveSmallIntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('secure', 'Secure'), ('medium', 'Medium'), ('high', 'High')], default='secure', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'employee',
                'verbose_name_plural': 'employees',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.PositiveSmallIntegerField()),
                ('risk_level', models.CharField(choices=[('secure', 'Secure'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('factors', models.JSONField(blank=True, default=dict)),
                ('trigger_reason', models.CharField(blank=True, default='', max_length=255)),
                ('snapshot_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_snapshots', to='employees.employee')),
            ],
            options={
                'verbose_name': 'employee risk snapshot',
                'verbose_name_plural': 'employee risk snapshots',
                'ordering': ['-snapshot_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'risk_level'], name='employees_e_organiz_280fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['organization', 'department'], name='employees_e_organiz_f61392_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['email'], name='employees_e_email_8f5bbc_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='uq_employee_org_email'),
        ),
        migrations.AddIndex(
            model_name='employeerisksnapshot',
            index=models.Index(fields=['employee', '-snapshot_date'], name='employees_e_employe_67cc58_idx'),
        ),
        migrations.AddIndex(
            model_name='employeerisksnapshot',
            index=models.Index(fields=['snapshot_date'], name='employees_e_snapsho_c3f012_idx'),
        ),
    ]
