# Generated by Django 5.1.15 on 2026-06-17 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('credential_harvesting', 'Credential Harvesting'), ('link_click', 'Link Click'), ('attachment', 'Attachment')], max_length=25)),
                ('subject', models.CharField(max_length=512)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('html_content', models.TextField(blank=True, default='')),
                ('plain_text_content', models.TextField(blank=True, default='')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'email template',
                'verbose_name_plural': 'email templates',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'category'], name='templates_e_organiz_1c01db_idx'), models.Index(fields=['organization', 'difficulty_level'], name='templates_e_organiz_9323f5_idx'), models.Index(fields=['organization', 'is_active'], name='templates_e_organiz_fb2dd2_idx')],
            },
        ),
    ]
