# Generated by Django 5.1.15 on 2026-06-22 14:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_infrastructuresetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('format', models.CharField(default='PDF', max_length=10)),
                ('file_size', models.CharField(blank=True, default='', max_length=20)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Archived', 'Archived'), ('Generating', 'Generating')], default='Generated', max_length=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('campaign_data', models.JSONField(blank=True, default=list)),
                ('department_data', models.JSONField(blank=True, default=list)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'report',
                'verbose_name_plural': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='reports_rep_organiz_ae5072_idx'), models.Index(fields=['organization', '-generated_at'], name='reports_rep_organiz_aed0f2_idx')],
            },
        ),
    ]
