# Generated by Django 5.1.15 on 2026-06-20 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_name', models.CharField(blank=True, default='', max_length=255)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('landing_domain', models.CharField(blank=True, default='', max_length=255)),
                ('landing_domain_verified', models.BooleanField(default=False)),
                ('email_provider', models.CharField(choices=[('microsoft_365', 'Microsoft 365'), ('google_workspace', 'Google Workspace'), ('sendgrid', 'SendGrid'), ('ses', 'Amazon SES'), ('other', 'Other')], default='other', max_length=20)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password_enc', models.TextField(blank=True, default='')),
                ('smtp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'infrastructure setting',
                'verbose_name_plural': 'infrastructure settings',
            },
        ),
    ]
